USE db_schema;

-- Total revenue generated
SELECT SUM(`quantityOrdered` * `priceEach`) AS revenue
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode`
JOIN orders_new odn 
    ON odn.`orderNumber` = od.`orderNumber`
WHERE odn.status = 'Shipped'
;

-- Revenue generated by each product line
SELECT `productLine`,
        SUM(`quantityOrdered` * `priceEach`) AS revenue
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode`
JOIN orders_new odn 
    ON odn.`orderNumber` = od.`orderNumber`
WHERE odn.status = 'Shipped'
GROUP BY `productLine`
ORDER BY revenue DESC
;

-- Revenue generated by each product 
SELECT `productName`,
        SUM(`quantityOrdered` * `priceEach`) AS revenue
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode`
JOIN orders_new odn 
    ON odn.`orderNumber` = od.`orderNumber`
WHERE odn.status = 'Shipped'
GROUP BY `productName`
ORDER BY revenue DESC
LIMIT 5
;

-- Top 5 & Bottom 5 products by revenue
(SELECT `productName`,
        SUM(`quantityOrdered` * `priceEach`) AS revenue,
        'Top' AS position
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode`
JOIN orders_new odn 
    ON odn.`orderNumber` = od.`orderNumber`
WHERE odn.status = 'Shipped'
GROUP BY `productName`
ORDER BY revenue DESC
LIMIT 5)
UNION ALL
(SELECT `productName`,
        SUM(`quantityOrdered` * `priceEach`) AS revenue,
        'Bottom' AS position
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode`
JOIN orders_new odn 
    ON odn.`orderNumber` = od.`orderNumber`
WHERE odn.status = 'Shipped'
GROUP BY `productName`
ORDER BY revenue ASC
LIMIT 5)
;

-- Top product in product line by revenue
WITH product_CTE AS (
    SELECT `productLine`,
            `productName`,
            SUM(`quantityOrdered` * `priceEach`) AS revenue,
            ROW_NUMBER() OVER(PARTITION BY `productLine` ORDER BY SUM(`quantityOrdered` * `priceEach`) DESC) AS row_num
    FROM products_new pn
    JOIN orderdetails od
        ON od.`productCode` = pn.`productCode`
    JOIN orders_new odn 
    ON odn.`orderNumber` = od.`orderNumber`
    WHERE odn.status = 'Shipped'
    GROUP BY `productLine`, `productName`
)
SELECT `productLine`,
        `productName`,
        revenue
FROM `product_CTE`
WHERE row_num = 1
;

-- Total purchasing_cost, profit and revenue
SELECT SUM(od.`quantityOrdered` * pn.`buyPrice`) AS purchasing_cost,
        SUM((od.`priceEach` - pn.`buyPrice`) * od.`quantityOrdered`) AS profit,
        SUM(od.`quantityOrdered` * od.`priceEach`) AS revenue
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode`
JOIN orders_new odn 
    ON odn.`orderNumber` = od.`orderNumber`
WHERE odn.status = 'Shipped'
;

-- Purchasing cost, profit and revenue by product line
SELECT `productLine`,
        SUM(od.`quantityOrdered` * pn.`buyPrice`) AS purchasing_cost,
        SUM((od.`priceEach` - pn.`buyPrice`) * od.`quantityOrdered`) AS profit,
        SUM(od.`quantityOrdered` * od.`priceEach`) AS revenue
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode`
JOIN orders_new odn 
    ON odn.`orderNumber` = od.`orderNumber`
WHERE odn.status = 'Shipped'
GROUP BY `productLine`
ORDER BY profit DESC
;

-- Top & Bottom 5 products by Purchasing cost, profit and revenue
(SELECT `productName`,
        SUM(od.`quantityOrdered` * pn.`buyPrice`) AS purchasing_cost,
        SUM((od.`priceEach` - pn.`buyPrice`) * od.`quantityOrdered`) AS profit,
        SUM(od.`quantityOrdered` * od.`priceEach`) AS revenue,
        'Top' AS position
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode`
JOIN orders_new odn 
    ON odn.`orderNumber` = od.`orderNumber`
WHERE odn.status = 'Shipped'
GROUP BY `productName`
ORDER BY profit DESC
LIMIT 5)
UNION ALL
(SELECT `productName`,
        SUM(od.`quantityOrdered` * pn.`buyPrice`) AS purchasing_cost,
        SUM((od.`priceEach` - pn.`buyPrice`) * od.`quantityOrdered`) AS profit,
        SUM(od.`quantityOrdered` * od.`priceEach`) AS revenue,
        'Bottom' AS position
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode`
JOIN orders_new odn 
    ON odn.`orderNumber` = od.`orderNumber`
WHERE odn.status = 'Shipped'
GROUP BY `productName`
ORDER BY profit ASC
LIMIT 5)
;

-- Total revenue by country 
WITH product_CTE AS (
    SELECT c.country,
            odn.status,
            SUM(od.`quantityOrdered` * od.`priceEach`) AS revenue,
            ROW_NUMBER () OVER(PARTITION BY odn.status ORDER BY SUM(od.`quantityOrdered` * od.`priceEach`) DESC) AS row_num
    FROM products_new pn
    JOIN orderdetails od
        ON od.`productCode` = pn.`productCode`
    JOIN orders_new odn
        ON odn.`orderNumber` = od.`orderNumber`
    JOIN customers_new c 
        ON c.`customerNumber` = odn.`customerNumber` 
    GROUP BY c.country, odn.status
)
SELECT country,
        revenue
FROM `product_CTE`
WHERE status = 'Shipped' 
;

-- Top 10 Revenue & orders by Customers
SELECT CONCAT(c.`contactFirstName`, " ", c.`contactLastName`) AS fullName,
        COUNT(od.`orderNumber`) AS orders,
        SUM(od.`quantityOrdered` * od.`priceEach`) AS revenue
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode`
JOIN orders_new odn
    ON odn.`orderNumber` = od.`orderNumber`
JOIN customers_new c 
    ON c.`customerNumber` = odn.`customerNumber`
GROUP BY CONCAT(c.`contactFirstName`, ' ', c.`contactLastName`)
ORDER BY revenue DESC
LIMIT 10;

-- Revenue by sales rep 
SELECT CONCAT(en.`firstName`, " ", en.`lastName`) AS fullName,
        SUM(od.`quantityOrdered` * od.`priceEach`) AS revenue
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode` 
JOIN orders_new odn
    ON odn.`orderNumber` = od.`orderNumber`
JOIN customers_new c 
    ON c.`customerNumber` = odn.`customerNumber`
JOIN employees_new en  
    ON en.`employeeNumber` = c.`salesRepEmployeeNumber`
GROUP BY CONCAT(en.`firstName`, " ", en.`lastName`)
ORDER BY revenue DESC
;

-- Revenue by sales manager
SELECT CONCAT(e2.`firstName`, " ", e2.`lastName`) AS managerName,
        SUM((od.`priceEach` - pn.`buyPrice`) * od.`quantityOrdered`) AS profit,
        SUM(od.`quantityOrdered` * od.`priceEach`) AS revenue
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode` 
JOIN orders_new odn
    ON odn.`orderNumber` = od.`orderNumber`
JOIN customers_new c 
    ON c.`customerNumber` = odn.`customerNumber`
JOIN employees_new e1  
    ON e1.`employeeNumber` = c.`salesRepEmployeeNumber`
JOIN employees_new e2
    ON e1.`reportsTo` = e2.`employeeNumber`
WHERE e2.`jobTitle` LIKE '%Manager%' 
GROUP BY CONCAT(e2.`firstName`, " ", e2.`lastName`)
ORDER BY revenue DESC
;

-- Revenue by territory 
SELECT ofn.territory,
        SUM((od.`priceEach` - pn.`buyPrice`) * od.`quantityOrdered`) AS profit,
        SUM(od.`quantityOrdered` * od.`priceEach`) AS revenue
FROM products_new pn
JOIN orderdetails od
    ON od.`productCode` = pn.`productCode` 
JOIN orders_new odn
    ON odn.`orderNumber` = od.`orderNumber`
JOIN customers_new c 
    ON c.`customerNumber` = odn.`customerNumber`
JOIN employees_new en  
    ON en.`employeeNumber` = c.`salesRepEmployeeNumber`
JOIN offices_new ofn
    ON ofn.`officeCode` = en.`officeCode`
GROUP BY ofn.territory
ORDER BY revenue DESC
;

